### ISSUE TITLE
Suggested Enhances

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#26]
Hi Allen,

Per our conversation yesterday the following are suggestions for possibly enhancing Homebase for RMH Providence.  

1. When a password is reset the person gets an email with the reset password.
2. When a volunteer is removed off of the Master Schedule or is no longer active they do not show up on the calendar.

**Comment by megandalster** [comment]
Thanks, Joanna, I’ll work on all 4 issues in the next 2 weeks.  Allen

On Aug 28, 2015, at 3:11 PM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen,

Per our conversation yesterday the following are suggestions for possibly enhancing Homebase for RMH Providence.

  1.  When a password is reset the person gets an email with the reset password.
  2.  When a volunteer is removed off of the Master Schedule or is no longer active they do not show up on the calendar.

**Comment by megandalster** [comment]
Hi Joanna and Sue,

I have implemented the second suggestion but not the first.  Now you should be able to remove a person from the master schedule and that person will be automatically removed from all future shifts (but not past shifts).  Let me know if this works.

As for emailing the person with a reset password, I cannot figure out how to do that.  So I must let it pass.  Let me know if this is a big issue for you -- if so, I'll look at it again.  Otherwise, I'll let it go.

Allen

**Comment by jopowers** [comment]
Hi Allen,

Thanks for your help with this - the first enhancement is huge for us, that way we don't have to worry about publishing our calendars weekly, this will allow us to offer the entire year and make adjustments without having to change every single week. Not a problem regarding the email option for the password.
