### ISSUE TITLE
Excel function not working in reports

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#35]
Hi Allen,

We are having trouble using the Excel function in the reports. I ran the October Birthday report today but when I hit submit, it did not allow me to load it into Excel. 

Thanks!

Joanna

**Comment by megandalster** [comment]
After you hit Submit, you then need to set your browser to this:

http://rmhp-homebase.myopensoftware.org/export.csv

Now the Excel file should download to your computer.

Feel free to call me if you want to walk through this one time.  207-841-1399

Allen

**Comment by jopowers** [comment]
Hi Allen,

I'm not sure I understand how to do this. I did click on the link you sent and it worked, but do we need to have this link every time we are trying to export a report to Excel?

**Comment by megandalster** [comment]
yes, every time you generate a report in Homebase, it will be different -- but it will share the same file name "export.csv" as the previous report you generated and downloaded.  So you need to change the url at the top of the browser from rmhp-homebase....../reports.csv to rmhp-homebase...../export.csv in order to force the download of your most recent report to your computer.  When you go to the Download folder on your computer, you should see all the different export.csv files that you downloaded -- now each one can be opened up separately in Excel.  Call me if you want to walk through any of this... 207-729-8111.

**Comment by jopowers** [comment]
Hi Allen,

Thank you for the offer, I think I will need a walk through. I hope you enjoyed your golf game and had a great weekend. I will touch base with you on Monday if that works?  

Thanks!

**Comment by megandalster** [comment]
Okay, I'll start a hangout with you around 9?  Allen

**Comment by jopowers** [comment]
The House doesn't open until 9:00 on Monday and I have to get the volunteers settled in can we make it 10 AM?

**Comment by megandalster** [comment]
Okay, 10 it is.  Have a good weekend!  Allen

**Comment by jopowers** [comment]
Thanks Allen - you too!

**Comment by jopowers** [comment]
Hi Allen- I think we missed each other this morning I had my google + open sorry if I missed the call.

**Comment by megandalster** [comment]
Hi Joanna,

Yipes, I’m sorry — I booted this call.

I’m free the rest of the day if you want to try again.

Allen

On Oct 5, 2015, at 11:15 AM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen- I think we missed each other this morning I had my google + open sorry if I missed the call.
