### ISSUE TITLE
Odd and Even weeks off on Calendars for 2016

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#36]
Hi Allen,

Sue and I have started to look ahead and we noticed an issue with the 2016 calendar.  When it changes over to the first week in January it should be an "Even" week however it reverts to an Odd week which means the volunteers on the master schedule are scheduled for the wrong week. For example Elizabeth Marcantonio  is on the Master Schedule as an Odd week (which is correct) however she is scheduled two weeks in a row once on 12/29 and the next week on 1/5/16 as well. That first week in January should be an even not odd. Thanks for looking into this for us!

**Comment by megandalster** [comment]
Hi Joanne,

Yes, this is an issue.  Right now, “odd” means “odd week of the year”, so that week 1 of each year is always odd.  That creates exactly the problem that you noted with Elizabeth, where she’s scheduled for two weeks in a row when one year ends and the next one begins.

I don’t know how to fix this without redefining what “odd” means.  Another approach might be to humbly explain to volunteers this problem and to ask for their understanding once a year when we roll over from an odd week at the end of the year to another odd week at the beginning of the next.

Too bad that a year can’t always have an even number of weeks :-)

Allen

On Oct 13, 2015, at 4:09 PM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen,

Sue and I have started to look ahead and we noticed an issue with the 2016 calendar. When it changes over to the first week in January it should be an "Even" week however it reverts to an Odd week which means the volunteers on the master schedule are scheduled for the wrong week. For example Elizabeth Marcantonio is on the Master Schedule as an Odd week (which is correct) however she is scheduled two weeks in a row once on 12/29 and the next week on 1/5/16 as well. That first week in January should be an even not odd. Thanks for looking into this for us!

**Comment by jopowers** [comment]
Hi Allen,

It seems to be affecting more than just the first week of the year. All of our volunteers that work every other week (odd or even) will now be on the wrong week for the entire 2016 year.  For example Liz is scheduled on the master schedule for odd weeks - she should be on 12/29 and then on the 1/12. I understand what you are saying about the first week, however it then throws off the entire schedule putting all of our folks on the wrong week if they are are every other week.

**Comment by megandalster** [comment]
Right, I see what you are saying.  I will work on a fix for this.

One way to fix it is to just do a 2-year cycle — Since every year has an odd number of weeks, every 2 years should have an even number of weeks.  Nobody cares if they are on an “odd” or “even” week of the year, as long as they stay on an every other week schedule without interruption.

Thanks Joanna, I will keep you posted when I figure out how to put this into the software.

Allen

On Oct 14, 2015, at 2:50 PM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen,

It seems to be affecting more than just the first week of the year. All of our volunteers that work every other week (odd or even) will now be on the wrong week for the entire 2016 year. For example Liz is scheduled on the master schedule for odd weeks - she should be on 12/29 and then on the 1/12. I understand what you are saying about the first week, however it then throws off the entire schedule putting all of our folks on the wrong week if they are are every other week.

**Comment by jopowers** [comment]
Yes  -thanks Allen, we appreciate all your help!

**Comment by megandalster** [comment]
Hi Joanna,

I have fixed this issue by making the first week of every year either 0 or 1 depending on whether the last week of the previous year was 53 or 52.  This is effectively a 2-year cycle, and it guarantees that people on an every-other-week cycle will not be jolted at the end of this year or any other year.

Gabriel, please replace the attached 3 scripts at the root level in the Homebase code base on the RMHProvidence.org server.  Please also let us all know when that is done.  Thanks!

Joanna, after Gabrielle installs the fix, you should see a slightly different header on the calendar page, looking like this:

Screen Shot 2015-10-15 at 10.39.23 AM.png

The header now shows the week number and whether or not it is even or odd at the right.  Moving forward with the “Next Week” tab, notice that even and odd alternate correctly at the end of this year and the beginning of 2016.

You will need to make the final correction by deleting all weeks in 2016 and re-adding them using the Manage Weeks tab.  Now check again and see that Liz’s odd week schedule is not interrupted at the end of the year.

But don’t do this final correction until Gabriel has installed the fix… let me know how it works.

Thanks,
Allen
