### ISSUE TITLE
Name not appearing on calendars

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#39]
Hi Allen,

I hope you are well and enjoying the season! Things are going well with Homebase the volunteers have been using and it seem to really like it.  We have had a few small things come in up that I was hoping you could advise us with. 

We have published the House calendar for the entire 2016 year. We need to do this since our volunteers sign up for an entire year at a time. I just added a new volunteer, her name is Barbara Wales, she is now volunteering every Tuesday from 1pm-5pm. I have her in the Master Schedule, but she does not appear on calendar at all. I tried to unpublish and republish the calendars and her name still does not appear. Is there a way we can fix this issue?

Thanks for the advice! 

Joanna

**Comment by megandalster** [comment]
Hi Joanna,

I’m glad things are going well with Homebase.

The situation you describe is not one that we took into account with the Homebase design.  So in short, it doesn’t handle gracefully the addition of a new volunteer to the master schedule because it doesn’t automatically update the already-generated weeks, whether they are published or unpublished.

The only way you can currently get the new person into her proper place on the calendar is to “remove” the future calendar weeks and then re-add them one-by-one.  But this isn’t any good for you, since everyone who has added themselves into future calendar weeks manually will be removed as well.

I need to fix this one.  It is similar to the situation where you remove a person from the master schedule and the software automatically removes them from future calendar weeks.  So I think I can do something with it.

Why don’t you post it as an issue, and I will commit to working on it during the next couple of weeks.  What I plan is for the software to automatically add any person to already-generated calendar weeks whenever you add them to the master schedule.  That seems to be what you need.

Let me know if this makes sense to you and we’ll keep moving forward.

Best,
Allen

On Dec 15, 2015, at 3:33 PM, jopowers <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Allen,

I hope you are well and enjoying the season! Things are going well with Homebase the volunteers have been using and it seem to really like it. We have had a few small things come in up that I was hoping you could advise us with.

We have published the House calendar for the entire 2016 year. We need to do this since our volunteers sign up for an entire year at a time. I just added a new volunteer, her name is Barbara Wales, she is now volunteering every Tuesday from 1pm-5pm. I have her in the Master Schedule, but she does not appear on calendar at all. I tried to unpublish and republish the calendars and her name still does not appear. Is there a way we can fix this issue?

Thanks for the advice!

Joanna

**Comment by jopowers** [comment]
Thanks for your help Allen - we appreciate it!

**Comment by megandalster** [comment]
This issue is now fixed.  Adding a person to the master schedule will automatically add that person to the same shift on all future calendar weeks.  The fix will show up when the software is updated on your web site.
