### ISSUE TITLE
Master Schedule Vacancy Issue

### ISSUE THREAD

**Issue by jopowers** [megandalster/rmhp-homebase#43]
When we put someone on the House master schedule it populates the calendar for the year. However, when we remove a person from that schedule (ie. they had to quit, etc.) and we delete the vacancy the vacancy still shows up for that shift for the entire year.  I have tried several times to delete the vacancy but it does not automatically do that for a shift, so I actually have to go week by week and delete the vancany on the calendar.

**Comment by megandalster** [comment]
This is now fixed, so that when you delete a person from the master schedule, there will be no vacancy on the master schedule and no vacancy on any of the weeks that the person had been scheduled.  

If you want to put another person in her place on the master schedule, you'll need to create a new slot there and then add the person.  As before, that person will automatically be added to the right calendar shifts for the whole year.  This fix will be effective as soon as your web host installs the corrected code that I will send separately.
